version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongo-agenteflutuanteia
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: agenteflutuanteia
    restart: unless-stopped

