spring:
  application:
    name: agenteflutuanteia
  data:
    mongodb:
      uri: "${MONGODB_URI}"
      database: "${MONGODB_NAME}"

server:
  port: "${SERVER_PORT:8089}"

gemini:
  api-key: "${GEMINI_API_KEY}"
  model: gemini-1.5-flash
  api-url: "https://generativelanguage.googleapis.com/v1beta/models"
chat:
  system-prompt: "Você é um assistente inteligente e prestativo. Responda de forma clara, objetiva e em português."
